apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: celery-worker
        imagePullPolicy: Never
        env:
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: CELERY_RESULT_BACKEND
          value: "rpc://"
